### ISSUE TITLE
Contibution for Hacktoberfest 2021

### ISSUE THREAD

**Issue by AryamanGurjar** [lahiruroot/Hacktoberfest-2021-04#6]
Hello sir,
Can i add a HTML page to your repository with CSS styling :-)

**Comment by lahiruroot** [comment]
Sure😊😊

**Comment by lahiruroot** [comment]
> Hello sir,
> Can i add a HTML page to your repository with CSS styling :-)

Sure

**Comment by Takane42** [comment]
Hello @lahiruroot ,
Can i add my arduino code to your repository for hacktoberfest 2021?
